name: stream-inspection
channels:
  - conda-forge
  - defaults
dependencies:
  # Node.js and development tools
  - nodejs>=20
  
  # SRT (Secure Reliable Transport) dependencies
  # Note: Using system FFmpeg (Homebrew/apt/etc.) which has SRT support
  # The conda FFmpeg doesn't include libsrt support
  # See docs/FFMPEG_INSTALLATION.md for detailed installation instructions
  - srt>=1.5.0
  
  # Additional streaming protocols and codecs
  - x264
  - x265
  
  # Network and security libraries
  - openssl>=3.0
  
  # Development and build tools
  - cmake
  - pkg-config
  - make
  
  # Python dependencies for scripts and utilities
  - python>=3.11
  - pip
  - requests
  - boto3
  - pyyaml
  
  # System utilities
  - curl
  - wget
  - jq
  
  # Additional pip dependencies
  - pip:
    - aws-cdk-lib>=2.100.0
    - constructs>=10.0.0
